config/routes.rb
Mybema::Application.routes.draw do
  require 'sidekiq/web'

  authenticate :admin do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  devise_for :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :articles, only: [:show]
  resources :discussions, except: [:show]
  resources :discussion_comments
  resources :sections

  get 'discussions/:slug' => 'discussions#show'
  get 'profile' => 'users#edit_profile'
  patch 'profile/update' => 'users#update_profile', as: :user

  get 'users/:username' => 'users#profile', as: :user_profile

  #Search
  get 'search' => 'search#results', as: :search

  # API
  namespace :api do
    get 'prefetch/articles' => 'search#typeahead_article_prefetch'
    get 'prefetch/discussions' => 'search#typeahead_discussion_prefetch'
  end

  # subscriptions

  post 'discussions/:slug/subscribe' => 'subscriptions#subscribe', as: :subscribe
  post 'discussions/:slug/unsubscribe' => 'subscriptions#unsubscribe', as: :unsubscribe

  # Admin section
  get 'admin' => 'admin/overview#index'
  get 'admin/users' => 'admin/users#index'
  put 'admin/discussions/:id/toggle-visibility' => 'admin/discussions#toggle_visibility', as: :admin_toggle_discussion_visibility
  put 'admin/comments/:id/toggle-visibility' => 'admin/discussion_comments#toggle_visibility', as: :admin_toggle_comment_visibility
  patch 'admin/guest-posting/toggle' => 'admin/app_settings#toggle_guest_posting', as: :admin_toggle_guest_posting
  get 'admin/profile' => 'admin/profile#edit', as: :admin_profile
  patch 'admin/profile' => 'admin/profile#update'

  scope :admin, module: 'admin' do
    resources :admins, only: [:index, :new, :create, :destroy], as: :administrators
    resources :guidelines, only: [:index, :new, :create, :destroy], as: :guidelines
    resources :discussions, only: [:index, :edit, :update, :destroy], as: :admin_discussions
    resources :discussion_categories, except: [:show], as: :admin_discussion_categories
    resources :comments, only: [:index, :edit, :update, :destroy], as: :admin_comments, controller: 'discussion_comments'
    resources :sections, as: :admin_sections do
      resources :articles, except: [:index, :show]
    end
    resources :hero_messages, only: [:update]
    resources :articles, only: :index, as: :admin_articles
    resources :app_settings
  end
end

app/views/shared/_customizations.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    // Update nav background color
    $('nav').css("background-color", "<%= @app.nav_bg_color %>");

    // Update nav link text color
    $('.nav--list li').css('color', '<%= @app.nav_link_color %>');

    // Update nav link text hover color
    $(".nav--li, .logo-wrapper").hover(function() {
      $(this).css('background-color', '<%= @app.nav_link_hover_color %>');
    }, function() {
      $(this).css("background-color", "<%= @app.nav_bg_color %>");
    });
  });
</script>

app/views/shared/_header.html.erb
<nav>
  <div class='nav-wrapper'>
    <div class='logo-wrapper'>
      <%= link_to image_tag(@app.logo), root_path, class: 'nav--logo' %>
    </div>

    <span class='desktop-categories'>
      <%= render 'shared/search' %>
    </span>

    <div class='nav--list'>
      <ul>
        <%= link_to discussions_path, class: 'nav--li' do %>
          <li>
            Discussions
          </li>
        <% end %>

        <%= link_to sections_path, class: 'nav--li' do %>
          <li>
            Articles
          </li>
        <% end %>

        <% if @current_user.logged_in? %>
          <%= link_to profile_path, class: 'nav--li' do %>
            <li>
              Profile
            </li>
          <% end %>
        <% end %>

        <% if current_admin %>
          <%= link_to admin_path, class: 'nav--li' do %>
            <li>
              Admin
            </li>
          <% end %>
        <% elsif @current_user.guest? %>
          <%= link_to new_user_session_path, class: 'nav--li' do %>
            <li>
              Log in
            </li>
          <% end %>
        <% else %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav--li' do %>
            <li>
              Log out
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<span class='mobile-categories'>
  <div class='mobile-search-wrapper'>
    <%= render 'shared/search' %>
  </div>
</span>

app/views/shared/_search.html.erb
<div class='home-search--wrapper'>
  <%= form_for :search_community, url: search_path, html: { method: 'get', class: 'home-search--form'} do |f| %>
    <%= text_field_tag :query, params[:query],
        placeholder: "Search the community",
        onfocus: "this.placeholder = ''",
        onblur: "this.placeholder = 'Search the community'",
        class: 'home-search--input' %>

    <%= f.submit "SEARCH", class: 'home-search--btn', name: nil %>
  <% end %>
</div>

app/views/shared/_single_community_item.html.erb
<article class='single-community-item'>
  <div class='single-community-item--avatar'>
    <%= image_tag(discussion.user_avatar(*avatar_opts), class: 'listed-user-avatar', alt: 'avatar') %>
  </div>

  <div class='single-community-item--lens'>
    <li class='post-item'>
      <% if discussion.admin_id? %>
        <span class='admin-post'><%= discussion.username %></span>
      <% else %>
        <%= user_link discussion %>
      <% end %>
    </li>

    <li class='post-item' momentTime='<%= l(discussion.updated_at, format: :moment) %>'>
      <%= discussion.updated_at.to_date %>
    </li>

    <%= link_to discussions_path(category: discussion.discussion_category.slug) do %>
      <li class='post-item--last'>
        <%= discussion.discussion_category.name %>
      </li>
    <% end %>

    <h2>
      <%= link_to discussion.title, discussion_path(discussion.slug) %>
    </h2>
  </div>

  <div class='single-community-item--mobile-name'>
    <% if discussion.admin_id? %>
      <span class='admin-post'><%= discussion.username %></span>
    <% else %>
      <%= user_link discussion %>
    <% end %>
  </div>

  <div class='single-community-item--mobile-title'>
    <h2>
      <%= link_to discussion.title, discussion_path(discussion.slug) %>
    </h2>
  </div>

  <div class='single-community-item--mobile-date' momentTime='<%= l(discussion.updated_at, format: :moment) %>'>
    <%= discussion.updated_at.to_date %>
  </div>

  <div class='single-community-item--comment-count'>
    <div class='single-community-item--comment-wrapper'>
      <%= discussion.discussion_comments_count %>
      <span class='replies'>
        <%= "response".pluralize(discussion.discussion_comments_count) %>
      </span>
    </div>
  </div>
</article>