config/routes.rb
Mybema::Application.routes.draw do
  require 'sidekiq/web'

  authenticate :admin do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  devise_for :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :articles, only: [:show]
  resources :discussions, except: [:show]
  resources :discussion_comments
  resources :sections

  get 'discussions/:slug' => 'discussions#show'
  get 'profile' => 'users#edit_profile'
  patch 'profile/update' => 'users#update_profile', as: :user

  get 'users/:username' => 'users#profile', as: :user_profile

  #Search
  get 'search' => 'search#results', as: :search

  # API
  namespace :api do
    get 'prefetch/articles' => 'search#typeahead_article_prefetch'
    get 'prefetch/discussions' => 'search#typeahead_discussion_prefetch'
  end

  # subscriptions

  post 'discussions/:slug/subscribe' => 'subscriptions#subscribe', as: :subscribe
  post 'discussions/:slug/unsubscribe' => 'subscriptions#unsubscribe', as: :unsubscribe

  # Admin section
  get 'admin' => 'admin/overview#index'
  get 'admin/users' => 'admin/users#index'
  put 'admin/discussions/:id/toggle-visibility' => 'admin/discussions#toggle_visibility', as: :admin_toggle_discussion_visibility
  put 'admin/comments/:id/toggle-visibility' => 'admin/discussion_comments#toggle_visibility', as: :admin_toggle_comment_visibility
  patch 'admin/guest-posting/toggle' => 'admin/app_settings#toggle_guest_posting', as: :admin_toggle_guest_posting
  get 'admin/profile' => 'admin/profile#edit', as: :admin_profile
  patch 'admin/profile' => 'admin/profile#update'

  scope :admin, module: 'admin' do
    resources :admins, only: [:index, :new, :create, :destroy], as: :administrators
    resources :guidelines, only: [:index, :new, :create, :destroy], as: :guidelines
    resources :discussions, only: [:index, :edit, :update, :destroy], as: :admin_discussions
    resources :discussion_categories, except: [:show], as: :admin_discussion_categories
    resources :comments, only: [:index, :edit, :update, :destroy], as: :admin_comments, controller: 'discussion_comments'
    resources :sections, as: :admin_sections do
      resources :articles, except: [:index, :show]
    end
    resources :hero_messages, only: [:update]
    resources :articles, only: :index, as: :admin_articles
    resources :app_settings
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @discussions  = Discussion.with_includes.visible.by_recency.limit(8)
  end
end

app/views/home/_hero.html.erb
<section class='homepage-hero'>
  <% if displayable_hero(@app.hero_message) %>
    <div class='home-hero-message'>
      <div id='dismiss-hero-msg' class='home-hero--dismiss-btn'>&times;</div>
      <div>
        <%= auto_link @app.hero_message %>
      </div>
    </div>
  <% end %>

  <div class="hero-section-container">
    <div class='hero-section'>
      <div class='hero-section--inner-wrapper'>
        <%= link_to discussions_path do %>
          <%= image_tag(@app.all_discussions_image, class: 'homepage-hero-image', alt: 'all discussions') %>
        <% end %>

        <div class='hero-section--description'>
          <div class="hero-section--blurb">
            View all of the community's categories and discussions
          </div>

          <%= link_to discussions_path do %>
            <button class='hero-cta'>All discussions</button>
          <% end %>
        </div>
      </div>
    </div>

    <div class='hero-section'>
      <div class='hero-section--inner-wrapper'>
        <%= link_to sections_path do %>
          <%= image_tag(@app.all_articles_image, class: 'homepage-hero-image', alt: 'all articles') %>
        <% end %>

        <div class='hero-section--description'>
          <div class="hero-section--blurb">
            Find tutorials and answers to frequently asked questions
          </div>

          <%= link_to sections_path do %>
            <button class='hero-cta'>All articles</button>
          <% end %>
        </div>
      </div>
    </div>

    <% if show_community_join_button? %>
      <div class='hero-section'>
        <div class='hero-section--inner-wrapper'>
          <%= link_to new_user_registration_path do %>
            <%= image_tag(@app.join_community_image, class: 'homepage-hero-image', alt: 'join community') %>
          <% end %>

          <div class='hero-section--description'>
            <div class="hero-section--blurb">
              Sign up for a more personalized experience
            </div>

            <%= link_to new_user_registration_path do %>
              <button class='hero-cta'>Join the community</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <div class='hero-section'>
      <div class='hero-section--inner-wrapper'>
        <%= link_to new_discussion_path do %>
          <%= image_tag(@app.new_discussion_image, class: 'homepage-hero-image', alt: 'start new discussion') %>
        <% end %>

        <div class='hero-section--description'>
          <div class="hero-section--blurb">
            Share something or ask the community a question
          </div>

          <%= link_to new_discussion_path do %>
            <button class='hero-cta'>Start a discussion</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'hero' %>

<section class='community-content'>
  <h1 class='discussion-index-header'>
    Recent discussions in the community:
  </h1>

  <div>
    <% @discussions.each do |discussion| %>
      <%= render partial: 'shared/single_community_item.html.erb', locals: { discussion: discussion } %>
    <% end %>
  </div>

  <h4 class='view-all-link'>
    <%= link_to 'View all discussions', discussions_path %>
  </h4>
</section>