config/routes.rb
Mybema::Application.routes.draw do
  require 'sidekiq/web'

  authenticate :admin do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  devise_for :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :articles, only: [:show]
  resources :discussions, except: [:show]
  resources :discussion_comments
  resources :sections

  get 'discussions/:slug' => 'discussions#show'
  get 'profile' => 'users#edit_profile'
  patch 'profile/update' => 'users#update_profile', as: :user

  get 'users/:username' => 'users#profile', as: :user_profile

  #Search
  get 'search' => 'search#results', as: :search

  # API
  namespace :api do
    get 'prefetch/articles' => 'search#typeahead_article_prefetch'
    get 'prefetch/discussions' => 'search#typeahead_discussion_prefetch'
  end

  # subscriptions

  post 'discussions/:slug/subscribe' => 'subscriptions#subscribe', as: :subscribe
  post 'discussions/:slug/unsubscribe' => 'subscriptions#unsubscribe', as: :unsubscribe

  # Admin section
  get 'admin' => 'admin/overview#index'
  get 'admin/users' => 'admin/users#index'
  put 'admin/discussions/:id/toggle-visibility' => 'admin/discussions#toggle_visibility', as: :admin_toggle_discussion_visibility
  put 'admin/comments/:id/toggle-visibility' => 'admin/discussion_comments#toggle_visibility', as: :admin_toggle_comment_visibility
  patch 'admin/guest-posting/toggle' => 'admin/app_settings#toggle_guest_posting', as: :admin_toggle_guest_posting
  get 'admin/profile' => 'admin/profile#edit', as: :admin_profile
  patch 'admin/profile' => 'admin/profile#update'

  scope :admin, module: 'admin' do
    resources :admins, only: [:index, :new, :create, :destroy], as: :administrators
    resources :guidelines, only: [:index, :new, :create, :destroy], as: :guidelines
    resources :discussions, only: [:index, :edit, :update, :destroy], as: :admin_discussions
    resources :discussion_categories, except: [:show], as: :admin_discussion_categories
    resources :comments, only: [:index, :edit, :update, :destroy], as: :admin_comments, controller: 'discussion_comments'
    resources :sections, as: :admin_sections do
      resources :articles, except: [:index, :show]
    end
    resources :hero_messages, only: [:update]
    resources :articles, only: :index, as: :admin_articles
    resources :app_settings
  end
end

app/models/guideline.rb
# == Schema Information
#
# Table name: guidelines
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Guideline < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/guidelines_controller.rb
class Admin::GuidelinesController < AdminsController
  def index
    @guidelines = Guideline.all.reverse
  end

  def new
    @guideline = Guideline.new
  end

  def create
    @guideline = Guideline.new guideline_params

    if @guideline.save
      redirect_to guidelines_path
    else
      render 'new'
    end
  end

  def destroy
    @guideline = Guideline.find(params[:id])

    if @guideline.destroy
      redirect_to guidelines_path
    end
  end

  private

  def guideline_params
    params.require(:guideline).permit(:name)
  end
end

app/views/admin/guidelines/index.html.erb
<section class='dashboard-container'>
  <h2 class='admin-section-header'>
    Community guidelines
  </h2>

  <div>
    <p class='guidelines-intro'>
      These are the contribution guidelines that your community should be adhering to. All of the guidelines you add are visible next to the discussion creation form <%= link_to 'found here', new_discussion_path %>. You can add and delete as many guidelines as you want. We'd recommend sticking between 8 and 9. All changes are reflected immediatly.
    </p>

    <div class='admin-btn-wrapper'>
      <%= link_to 'add guideline', new_guideline_path, class: 'admin-btn green-btn' %>
    </div>
  </div>

  <table class='table table-hover'>
    <thead>
      <tr>
        <th>Guidelines</th>
        <th class='ctr-txt'>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @guidelines.each do |guideline| %>
        <tr>
          <td>
            <%= guideline.name %>
          </td>

          <td class='ctr-txt'>
            <%= link_to 'delete', guideline_path(guideline), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/guidelines/new.html.erb
<section class='guidelines-form--wrapper'>
  <h2>
    New guideline:
  </h2>

  <div class='guideline-form' %>
    <%= form_for @guideline do |f| %>
      <div>
        <% if @guideline.errors.any? %>
          <ul>
            <% @guideline.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        <% end %>

        <div class='discussion-form--body'>
          <%= f.text_field :name, class: 'discussion-form--input' %>
        </div>
      </div>

      <footer>
        <%= f.submit "add guideline", class: "greenbutton" %>
      </footer>
    <% end %>
  </div>

  <%= link_to 'Cancel and return to list of guidelines', guidelines_path, class: 'discussion-form--cancel' %>
</section>